language: generic
sudo: required
service:
    - docker

before_install:
    - docker build -t y0shinubu/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true y0shinubu/docker-react npm run test -- --coverage